### ISSUE TITLE
Infringiment of copyright

### ISSUE THREAD

**Issue by Ragnok123** [kaliiks/GTAnticheat#1]
Though thic code is rewrite, but still this is a copy of private source, owned by GameTeam.cz.

So, cause of infringiment of copyright (owned by GameTeam.cz project, GameTeam PE is only part of project), it's required to remove this source from public using engine (Github).

**Comment by Creeperface01** [comment]
I agree with @Ragnok123 repository content is really owned by GameTeam.cz and cannot be shared. So we recommend you to remove it from there or it will be deleted automatically.

**Comment by majovec** [comment]
Chlapci vy jste komici gameteam není žádná obchodní značka která tak že nic ne porušuje a Jeniku měl sis dát aspoň licenci či založit private repozitar tak to máš po pici

**Comment by kaliiks** [comment]
Source was shared on http://gitter.im/Nukkit

**Comment by Creeperface01** [comment]
https://en.wikipedia.org/wiki/Copyright maybe you should know about this.

**Comment by kaliiks** [comment]
Sorry, but you must have license agreement for the project, if you or your organization doesn't have it, then the links you sent me are totally useless and also still your project was shared on http://gitter.im/Nukkit [https://www.dropbox.com/s/g1iujv4fgtqaz88/GAC.jar?dl=0](here exactly), so I still don't see any reason to take this plugin down from github

**Comment by Creeperface01** [comment]
Hmm very strange so you think it was just a dream and I have never coded GTAnticheat? Really interesting to hear thanks for noticing me. But your idea is wrong and I'm the only owner of this plugin and maybe rather than asking for license (because if its on private repository I dont need it) Is better to ask where and from did you get permissions to share or edit this content if you could tell me

**Comment by kaliiks** [comment]
@Creeperface01 If you don't have license, then it's only your problem

**Comment by Creeperface01** [comment]
Answer my question. BTW if you use someone's work you must always know whos it is

**Comment by kaliiks** [comment]
Your anticheat may be just copied and ported to Nukkit..

**Comment by Creeperface01** [comment]
Answer my question again.

**Comment by kaliiks** [comment]
Which question? I already gave you answer

**Comment by Creeperface01** [comment]
Who is the owner then? even if I copied it and stolen it as you did it doesn't give permissions to anybody to share or infringiment a copyright

**Comment by kaliiks** [comment]
First of all, I didn't stole anything, the anticheat was posted on gitter.im/Nukkit without license and maybe I know the owner, but I don't have reason to tell you..

**Comment by Creeperface01** [comment]
You don't know anything.. As I said stolen or modified copyrighted content is still under copyright even if the license was removed etc. It does not make sense where you got it.

**Comment by kaliiks** [comment]
![image](https://user-images.githubusercontent.com/21057270/35290490-b45180fc-006a-11e8-919b-be6ab04dab0e.png)
Nezapoměň to poslat github adminům, psal jsem schvalně anglicky ať mají radost a nemuseji si to překládat :D Tak hodně štěstí a krásný zbytek dne

**Comment by kaliiks** [comment]
https://github.com/majovec/TajnaMyskaVec2 toto tě očividně nezajímá jak vidím 🗡  Nebo jsi to snad vzdal?
